/* The callback function for Google Singin button
 * Send authorization code received from Google API (one-time-use code)
 * and state token to the server(anti-forgery session token generated by server)
 */
function signInCallback(authResult) {
    console.log("Javascript signInCallback function")
    if (authResult['code']) {
        // user is authorized, hide the google sigin in button
        $('#signinButton').attr('style', 'display: none');

        // send the one-time-code to the server
        $.ajax({
            type: 'POST',
            url: '/gconnect?state={{STATE}}', // send state to server
            data: authResult['code'],
            contentType: 'application/octet-stream; charset=UTF-8',
            success: function(result) { // sucessfully sent request to server
                // verify server response
                if (result) {
                    $('#signInResult').html('You have logged in! </br>' +
                        result + '</br>Redirecting')
                    setTimeout(function() {
                          window.location.href = "/item_catalog";
                          },
                          4000);
                } else if (authResult['error']) {
                    console.log('There was an error: ' +
                                authResult['error']);
                }
            },
            processData: false // don't process data into jquery string
        });
    } else { // there was an error
        $('#signInResult').html('Failed to make server call, please ' +
                                'check your configuration');
    }
}
